### PR TITLE
PR 343 review

### PR DESCRIPTION
**Pull request by fpistm**
Hi @zoomx 
I've made a quick review and do some update:
 * Remove trailing space
 * Unify file format (Unix)
 * Add STM Morpho connector pin mapping
 * Clean up some comments

If you are agreed, could you squash all your commits for the L073 and this one into one commit then force update to your branch to update https://github.com/stm32duino/Arduino_Core_STM32/pull/343
Thanks

### CODE REVIEW

**Comment by fpistm** [comment]
Merci

**Comment by zoomx** [comment]
I agree, of course, and merged it but I don't know how to force update to my branch!

**Comment by fpistm** [comment]
No worries, I will squash the 3 commits in one when I will merge your PR. ;)

**Comment by zoomx** [comment]
Great!

**Pull request merged**
